hyper_param_optimisation: {"n_estimators":{"low":1, "high":2000},
                            "max_depth":{"low":1, "high":10},
                            "min_child_weight":{"low":1, "high":10},
                            "learning_rate":{"low":0.01, "high":0.7},
                            "min_split_loss":{"low":0, "high":5},
                            "colsample_bytree":{"low":0.01, "high":1},
                            "subsample":{"low":0.01, "high":1}}
