data:
  raw_data_path: data/raw/base_projet_teleco.csv
  external_data_path: data/external/marque_telephone.csv
  df_train : data/processed/df_train.csv
  df_val : data/processed/df_val.csv
  x_train : data/interim_demo/x_train.csv
  x_val : data/interim_demo/x_val.csv

features_info:
  target: "AFTERGRACE_FLAG"
  new_features:
  columns_to_drop:

encoding_scaling:
  list_cont_col:
  list_binary_col:
  list_cat_col_OHE:
  list_cat_col_TE:


random_state: 14

models: models/scoring_model.pkl

optimisation_metric: "f1_micro"

reports:
  df_train_summary:
  target_distrib_groupby_cat_features:
  target_distrib_groupby_num_features:
  corr_matrix_df_train:


logging:
  log_file_path: logs/log.txt
  log_level: INFO

streamlit:
  page_title: "Spending Score Prediction Web App"
  page_icon: ":bar_chart:"